# Auto-generated from .repo.toml by 'just repo_toml_generate'
# DO NOT EDIT THIS FILE MANUALLY - regenerate with: just repo_toml_generate

# About section
REPO_DESCRIPTION="https://www.chicks.net/ web site built with Hugo and PaperMod 📃"
REPO_LICENSE=""
REPO_TOPICS="blog,business,freesoftware,hugo-site,justfile,trains,website"

# URLs section
REPO_GIT_SSH="git@github.com:chicks-net/www-chicks-net.git"
REPO_WEB_URL="https://github.com/chicks-net/www-chicks-net"

# Derived values
REPO_ORG_NAME="chicks-net"
REPO_REPO_NAME="www-chicks-net"

# Feature flags (strings: "true" or "false")
FLAG_CLAUDE="false"
FLAG_CLAUDE_REVIEW="false"
FLAG_COPILOT_REVIEW="false"
FLAG_STANDARD_RELEASE="true"

# Topics as array (for iteration)
REPO_TOPICS_ARRAY=(
    "blog"
    "business"
    "freesoftware"
    "hugo-site"
    "justfile"
    "trains"
    "website"
)
