# .repo.toml

[about]
description = "https://www.chicks.net/ web site built with Hugo and PaperMod 📃"
topics = ["blog", "business", "freesoftware", "hugo-site", "justfile", "trains", "website"]

[urls]
git_ssh = "git@github.com:chicks-net/www-chicks-net.git"
web_url = "https://github.com/chicks-net/www-chicks-net"

[flags]
claude = true
claude-review = true
copilot-review = true
standard-release = true
