baseURL = 'https://www.chicks.net/'
languageCode = 'en-us'
title = 'Christopher Hicks Personal Site'

#theme = ["github.com/theNewDynamic/gohugo-theme-ananke"]
theme = ["github.com/adityatelange/hugo-PaperMod"]

[[module.imports]]
path = "github.com/adityatelange/hugo-PaperMod"

[params]
body_classes = "avenir bg-near-white"

[[params.ananke_socials]]
name = "github"
url = "https://github.com/chicks-net"

[[params.ananke_socials]]
name = "linkedin"
url = "https://www.linkedin.com/in/chicks2fini"

[[params.ananke_socials]]
name = "youtube"
url = "https://www.youtube.com/@ChristopherHicksFINI"

[[params.ananke_socials]]
name = "stackoverflow"
url = "https://stackexchange.com/users/2276315/chicks"
